typography_spectrum: 0.31625925833857294
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b4b4b4'
    - '#878787'
    - '#5c5c5c'
  brandStrength: 0.13076238061808568
  lightness: 0.2708609294845252
  saturation: 0.6793171353945232
  rhythmicContrast: 0.8658187156233309
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4119111898404979
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c1a4d2b-c3b3-4a4b-a905-46e5c8b07c21.png
name: Energy Holistic Health
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'My Journey '
    id: 084934d4-d276-4d2a-81c2-88ae48fff578
    type: content
  - name: Product Links
    id: 5ff1ef31-f618-4785-b625-34ae814382df
    type: content
favicon: null
title: Energy Holistic Health
content: []
description: Mindy Jones Lee - Integrative Health Practitioner
purpose: []
