name: Energy Holistic Health
favicon: null
layout_spectrum: 0.2452479861676693
typography_spectrum: 0.36651854356750846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4cff29'
    - '#ffffff'
    - '#2272be'
    - '#000000'
    - '#e7a98a'
  brandStrength: 0.3125
  lightness: 0.655744536081329
  saturation: 0.3125
  rhythmicContrast: 0.6302040941081941
purpose: []
