name: Energy Holistic Health
favicon: null
layout_spectrum: 0.25792
typography_spectrum: 0.43126
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b4b4b4'
    - '#878787'
    - '#5c5c5c'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
